/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get OpenAPI schema
         * @description Returns the complete OpenAPI 3.0 schema for the application
         */
        get: operations["3d5b2673f8a90c3e99e595b8551a6d2d"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Order: {
            /**
             * Format: int64
             * @description Order ID
             */
            id?: number;
            /** @description Order title */
            title: string;
            /**
             * Format: decimal
             * @description Order amount
             */
            amount: number;
            /**
             * @description Order status
             * @enum {string}
             */
            status: "pending_payment" | "completed" | "cancelled" | "refunded";
            /** @description Order description */
            description?: string | null;
            /**
             * Format: int64
             * @description ID of the user who owns this order
             */
            user_id: number;
            /** @description Credit note number for refunded orders */
            credit_note_number?: string | null;
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            created_at?: string;
            /**
             * Format: date-time
             * @description Last update timestamp
             */
            updated_at?: string | null;
            /**
             * Format: date-time
             * @description Soft delete timestamp
             */
            deleted_at?: string | null;
        };
        Transaction: {
            /**
             * Format: int64
             * @description Transaction ID
             */
            id?: number;
            /**
             * Format: int64
             * @description ID of the user this transaction belongs to
             */
            user_id: number;
            /**
             * @description Transaction type
             * @enum {string}
             */
            type: "credit" | "debit";
            /**
             * Format: decimal
             * @description Transaction amount
             */
            amount: number;
            /**
             * @description Transaction status
             * @enum {string}
             */
            status: "active" | "cancelled";
            /** @description Transaction description */
            description?: string | null;
            /**
             * Format: int64
             * @description ID of the user who created this transaction
             */
            created_by: number;
            /**
             * Format: int64
             * @description ID of the related order
             */
            order_id?: number | null;
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            created_at?: string;
            /**
             * Format: date-time
             * @description Last update timestamp
             */
            updated_at?: string | null;
        };
        User: {
            /**
             * Format: int64
             * @description User ID
             */
            id?: number;
            /** @description User's full name */
            name: string;
            /**
             * Format: email
             * @description User's email address
             */
            email: string;
            /**
             * Format: decimal
             * @description User's wallet balance
             */
            wallet_amount: number;
            /**
             * Format: date-time
             * @description Email verification timestamp
             */
            email_verified_at?: string | null;
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            created_at?: string;
            /**
             * Format: date-time
             * @description Last update timestamp
             */
            updated_at?: string | null;
            /**
             * Format: date-time
             * @description Soft delete timestamp
             */
            deleted_at?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "3d5b2673f8a90c3e99e595b8551a6d2d": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI schema */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
}
